import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import Link from "next/link";

const graphcms = new GraphQLClient(
  "https://api-ap-south-1.graphcms.com/v2/cl3rbzoet8srg01xk3ialfs6j/master"
);

const QUERY = gql`
  {
    projects {
      title
      slug
    }
  }
`;

export async function getStaticProps() {
  const { projects } = await graphcms.request(QUERY);

  return {
    props: {
      projects,
    },
  };
}

export default function Home({ projects }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hi! I'm Avidu, an Web DEV from Ceylon.</h1>

      {/* NAVIGATION */}
      <nav></nav>

      {/* HERO */}
      <div></div>

      {/* SERVICES */}
      <div></div>

      {/* WHY ME */}
      <div></div>

      {/* PROJECT */}
      <div>
        <div>
          <h2>PROJECTS</h2>
        </div>
        <div>
          {projects.map(({ title, slug }) => (
            <ul key={slug}>
              <li>
                <Link key={slug} href={`/project/$slug`}>
                  {title}
                </Link>
              </li>
            </ul>
          ))}
        </div>
      </div>

      {/* CONTACT */}
      <div></div>

      {/* FOOTER */}
      <footer></footer>
    </div>
  );
}
